### PR TITLE
pmix: added testing with and without dstore

### PR DESCRIPTION
**Pull request by karasevb**
- Testing with/without dstore

- Fixed test status: the test are fail if one of any tests return a fail code.

### CODE REVIEW

**Comment by karasevb** [comment]
@artpol84 please review

**Comment by karasevb** [comment]
In this PR has been solved the problem, which introduced in https://github.com/pmix/master/issues/147

**Comment by artpol84** [comment]
@karasevb please, add per-process exit status check (using `-o` option of pmix_test)

**Comment by artpol84** [comment]
Let's probably do this as a separate PR. I need this changes now.

**Pull request merged**
