### PR TITLE
Use double-dash on multi-char options

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@artemry-mlnx I think this caught the problems, but I might have missed some

**Comment by artemry-mlnx** [comment]
@rhc54 could you please fix these ones?

-mca
https://github.com/mellanox-hpc/jenkins_scripts/blob/e7cc9a4d3ac8eb941c5073aaf17657f075459474/jenkins/ompi/ompi_test.sh#L259
https://github.com/mellanox-hpc/jenkins_scripts/blob/e7cc9a4d3ac8eb941c5073aaf17657f075459474/jenkins/ompi/ompi_test.sh#L511
https://github.com/mellanox-hpc/jenkins_scripts/blob/e7cc9a4d3ac8eb941c5073aaf17657f075459474/jenkins/ompi/ompi_test.sh#L518
https://github.com/mellanox-hpc/jenkins_scripts/blob/e7cc9a4d3ac8eb941c5073aaf17657f075459474/jenkins/ompi/ompi_test.sh#L525
https://github.com/mellanox-hpc/jenkins_scripts/blob/e7cc9a4d3ac8eb941c5073aaf17657f075459474/jenkins/ompi/ompi_test.sh#L533
https://github.com/mellanox-hpc/jenkins_scripts/blob/e7cc9a4d3ac8eb941c5073aaf17657f075459474/jenkins/ompi/ompi_test.sh#L535

-np
https://github.com/mellanox-hpc/jenkins_scripts/blob/e7cc9a4d3ac8eb941c5073aaf17657f075459474/jenkins/ompi/ompi_test.sh#L576

**Comment by rhc54** [comment]
Okay, I fixed those - please feel free to take it from here

**Comment by artemry-mlnx** [comment]
Found one more place remaining:
https://github.com/mellanox-hpc/jenkins_scripts/blob/c9442658dc74e0d3deca9f16c09e06df6af5de5a/jenkins/ompi/ompi_test.sh#L863

**Comment by rhc54** [comment]
I went ahead and fixed it. However, it might be more efficient if you simply fixed them from here rather than pointing them out to me 😄

**Comment by artemry-mlnx** [comment]
@rhc54 thanks for the fix.
I've run Mellanox Open MPI CI (for Open MPI master) to verify the scripts ([link](https://dev.azure.com/mlnx-swx/mellanox-ompi/_build/results?buildId=200&view=logs&j=05ee1795-5e75-566a-c260-61630d0851a3&t=32a347b2-22db-5350-4063-e70977d04423)).

**Pull request merged**
